### ISSUE TITLE
[BUG] - Port check in edge test intermittently failing

### ISSUE THREAD

**Issue by newhoggy** [input-output-hk/cardano-node#2075]
**Internal**

**Summary**
The port check in the edge test is intermittently failing.

**Steps to reproduce**
1. Create a PR on `cardano-node` repository and retry until you get the described failure.

**Expected behavior**

**System info (please complete the following information):**
- Environment: packet-ipxe-1.ci.iohkdev.io

**Comment by newhoggy** [comment]
Example 1:

* https://hydra.iohk.io/build/4749744/nixlog/5

Example output:

```
machine: must succeed: systemctl status cardano-node
(6.45 seconds)
machine: must succeed: stat /run/cardano-node
(0.85 seconds)
machine: must succeed: stat /run/cardano-node/node.socket
(0.24 seconds)
machine: must succeed: sleep 15
machine # [   58.132380] nscd[791]: 791 checking for monitored file `/etc/netgroup': No such file or directory
(15.67 seconds)
machine: must succeed: nc -z 127.0.0.1 12798
machine: output: 
error: 
Traceback (most recent call last):
  File "/nix/store/3q4fr94l6q9drjqpx4kwiydynz5igy1m-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 901, in run_tests
    exec(tests, globals())
  File "<string>", line 1, in <module>
  File "<string>", line 8, in <module>
  File "/nix/store/3q4fr94l6q9drjqpx4kwiydynz5igy1m-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 423, in succeed
    raise Exception(
Exception: command `nc -z 127.0.0.1 12798` failed (exit code 1)
cleaning up
killing machine (pid 6)
(0.00 seconds)
builder for '/nix/store/z795qcrmy68m3fklf26khswwmmjj79rr-vm-test-run-cardano-node-edge-test.drv' failed with exit code 1
```

**Comment by newhoggy** [comment]
Example 2:

https://hydra.iohk.io/build/4733118/nixlog/6

```
machine: must succeed: systemctl status cardano-node
(8.81 seconds)
machine: must succeed: stat /run/cardano-node
(3.19 seconds)
machine: must succeed: stat /run/cardano-node/node.socket
(0.01 seconds)
machine: must succeed: sleep 15
machine # [   40.687475] nscd[787]: 787 checking for monitored file `/etc/netgroup': No such file or directory
machine # [   52.442678] cardano-node-start[726]: Listening on http://127.0.0.1:12798
(15.39 seconds)
machine: must succeed: nc -z 127.0.0.1 12798
machine # Connection to 127.0.0.1 12798 port [tcp/*] succeeded!
(7.64 seconds)
machine: must succeed: nc -z 127.0.0.1 3001
machine: output: 
error: 
Traceback (most recent call last):
  File "/nix/store/3q4fr94l6q9drjqpx4kwiydynz5igy1m-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 901, in run_tests
    exec(tests, globals())
  File "<string>", line 1, in <module>
  File "<string>", line 9, in <module>
  File "/nix/store/3q4fr94l6q9drjqpx4kwiydynz5igy1m-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 423, in succeed
    raise Exception(
Exception: command `nc -z 127.0.0.1 3001` failed (exit code 1)
cleaning up
killing machine (pid 6)
(0.00 seconds)
builder for '/nix/store/ghdlk4v9v43kqv4ljiw5l6qs44jvvb59-vm-test-run-cardano-node-edge-test.drv' failed with exit code 1
```

**Comment by newhoggy** [comment]
Example 3: https://hydra.iohk.io/build/4792078/nixlog/5

**Comment by newhoggy** [comment]
The edge test is still failing intermittently:  https://hydra.iohk.io/build/5002298/nixlog/5

```
machine: must succeed: nc -z 127.0.0.1 12798
machine: output: 
error: 
Traceback (most recent call last):
  File "/nix/store/z3wh11zijs27ai4iybhrg895ks3nbg68-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 901, in run_tests
    exec(tests, globals())
  File "<string>", line 1, in <module>
  File "<string>", line 8, in <module>
  File "/nix/store/z3wh11zijs27ai4iybhrg895ks3nbg68-nixos-test-driver/bin/.nixos-test-driver-wrapped", line 423, in succeed
    raise Exception(
Exception: command `nc -z 127.0.0.1 12798` failed (exit code 1)
```
