### ISSUE TITLE
[BUG] - 

### ISSUE THREAD

**Issue by kelvingevers** [input-output-hk/cardano-node#3117]
i followed the guide but at getBalance() I get this error.

mallet> getBalance()
Thrown:
Error: Invalid JSON RPC response: undefined
at Object.InvalidResponse (/mnt/c/pr0/mallet/lib/web3/web3/errors.js:38:16)
at HttpProvider.send (/mnt/c/pr0/mallet/lib/web3/web3/httpprovider.js:102:18)
at RequestManager.send (/mnt/c/pr0/mallet/lib/web3/web3/requestmanager.js:65:32)
at Eth.send [as getBalance] (/mnt/c/pr0/mallet/lib/web3/web3/method.js:145:58)
at Mallet.getBalance (/mnt/c/pr0/mallet/lib/mallet.js:238:26)

**Comment by james-iohk** [comment]
@kelvingevers Looks like this is not related to cardano node. Please follow instructions over in the repo for Mallet and raise any issues you find there https://github.com/input-output-hk/mallet.
