### ISSUE TITLE
Node doesn't connect (bad block)

### ISSUE THREAD

**Issue by kevinhammond** [input-output-hk/cardano-node#759]
[https://iohk.zendesk.com/agent/tickets/92084](https://iohk.zendesk.com/agent/tickets/92084)

Log shows:

```
[2020-03-01T01:02:53.0866Z] [debug] AdaApi::syncProgress error: {
  "stack": "Error: write EPROTO 101057795:error:0407006A:rsa routines:RSA_padding_check_PKCS1_type_1:block type is not 01:c:\\projects\\electron\\vendor\\node\\deps\\openssl\\openssl\\crypto\\rsa\\rsa_pk1.c:103:\n101057795:error:04067072:rsa routines:RSA_EAY_PUBLIC_DECRYPT:padding check failed:c:\\projects\\electron\\vendor\\node\\deps\\openssl\\openssl\\crypto\\rsa\\rsa_eay.c:705:\n101057795:error:1408D07B:SSL routines:ssl3_get_key_exchange:bad signature:c:\\projects\\electron\\vendor\\node\\deps\\openssl\\openssl\\ssl\\s3_clnt.c:2032:\n\n    at exports._errnoException (util.js:1050:11)\n    at WriteWrap.afterWrite [as oncomplete] (net.js:813:14)",
  "message": "write EPROTO 101057795:error:0407006A:rsa routines:RSA_padding_check_PKCS1_type_1:block type is not 01:c:\\projects\\electron\\vendor\\node\\deps\\openssl\\openssl\\crypto\\rsa\\rsa_pk1.c:103:\n101057795:error:04067072:rsa routines:RSA_EAY_PUBLIC_DECRYPT:padding check failed:c:\\projects\\electron\\vendor\\node\\deps\\openssl\\openssl\\crypto\\rsa\\rsa_eay.c:705:\n101057795:error:1408D07B:SSL routines:ssl3_get_key_exchange:bad signature:c:\\projects\\electron\\vendor\\node\\deps\\openssl\\openssl\\ssl\\s3_clnt.c:2032:\n",
[2020-03-01T01:02:53.0867Z] [debug] AdaApi::syncProgress error: {
  "stack": "Error: write EPROTO 101057795:error:0407006A:rsa routines:RSA_padding_check_PKCS1_type_1:block type is not 01:c:\\projects\\electron\\vendor\\node\\deps\\openssl\\openssl\\crypto\\rsa\\rsa_pk1.c:103:\n101057795:error:04067072:rsa routines:RSA_EAY_PUBLIC_DECRYPT:padding check failed:c:\\projects\\electron\\vendor\\node\\deps\\openssl\\openssl\\crypto\\rsa\\rsa_eay.c:705:\n101057795:error:1408D07B:SSL routines:ssl3_get_key_exchange:bad signature:c:\\projects\\electron\\vendor\\node\\deps\\openssl\\openssl\\ssl\\s3_clnt.c:2032:\n\n    at exports._errnoException (util.js:1050:11)\n    at WriteWrap.afterWrite [as oncomplete] (net.js:813:14)",
  "message": "write EPROTO 101057795:error:0407006A:rsa routines:RSA_padding_check_PKCS1_type_1:block type is not 01:c:\\projects\\electron\\vendor\\node\\deps\\openssl\\openssl\\crypto\\rsa\\rsa_pk1.c:103:\n101057795:error:04067072:rsa routines:RSA_EAY_PUBLIC_DECRYPT:padding check failed:c:\\projects\\electron\\vendor\\node\\deps\\openssl\\openssl\\crypto\\rsa\\rsa_eay.c:705:\n101057795:error:1408D07B:SSL routines:ssl3_get_key_exchange:bad signature:c:\\projects\\electron\\vendor\\node\\deps\\openssl\\openssl\\ssl\\s3_clnt.c:2032:\n",


```

**Comment by kevinhammond** [comment]
This is another no connection error but I don't think it's related

https://iohk.zendesk.com/agent/tickets/92089

"app":["daedalus"],"msg":"AdaApi::getNetworkInfo error","pid":"","sev":"error","thread":""}
essing":false,"writecb":null,"writelen":0,"bufferedRequest":null,"lastBufferedRequest":null,"pendingcb":0,"prefinished":false,"errorEmitted":false,"emitClose":true,"bufferedRequestCount":0,"corkedRequestsFree":{"next":null,"entry":null}},"writable":true,"_events":{"rotated":[null,null]},"_eventsCount":3,"chunks":[],"options":{"size":5242880,"path":"Logs/pub/","maxFiles":4},"size":0},"cliBin":"C:\\Program Files\\Daedalus Flight\\cardano-cli.exe"},"launcherConfig":{"networkName":"mainnet","stateDi
":0,"bufferedRequest":null,"lastBufferedRequest":null,"pendingcb":0,"prefinished":false,"errorEmitted":false,"emitClose":true,"bufferedRequestCount":0,"corkedRequestsFree":{"next":null,"entry":null}},"writable":true,"_events":{"rotated":[null,null]},"_eventsCount":3,"chunks":[],"options":{"size":5242880,"path":"Logs/pub/","maxFiles":4},"size":0},"installSignalHandlers":false,"tlsConfiguration":{"caCert":"C:\\Users\\rober\\AppData\\Roaming\\Daedalus Flight\\tls\\server\\ca.crt","svCert":"C:\\User

**Comment by dorin100** [comment]
The user who reported https://iohk.zendesk.com/agent/tickets/92089 is saying that this is not reproducible (into the Zendesk ticket)
